Add server and client
Matthew3000/gophkeeper pull request #1
Opened 2023-03-14 21:50 UTC by Matthew3000

2023-03-20 14:30 UTC, Matthew3000 commented
> <img alt="image" width="745" src="https://user-images.githubusercontent.com/554425/226322543-43e19296-1952-4c5c-b962-dce2d5c54e6f.png">
> тестов нет :(

Я понимаю, что нет
остальное нормально?

2023-03-23 00:25 UTC, Matthew3000 commented
Здесь два теста:
1. Для сервера: покрывает все хендлеры и по цепочке — всё общение с бд
2. Для клиента: покрывает всё, включая общение с сервером и локальным хранилищем. Не покрывает общение с юзером.

Будет ли этого достаточно для принятия работы?

2023-03-24 09:18 UTC, tmvrus requested changes
- покрытие все еще меньше 80%
- множественное дублирования кода
- параметры тестов зашиты в код
- потерянные return
-  использование fmt для логирования

2023-03-24 09:18 UTC, tmvrus commented on internal/tools/gzip.go
> +			fmt.Println(err)
логирование пакетом fmt

2023-03-24 09:18 UTC, tmvrus commented on internal/tools/gzip.go
> +			_ = gzipReader.Close()
ошибки все же лучше обрабатывать хоть как-то

2023-03-24 09:18 UTC, tmvrus commented on internal/tools/crypto.go
> +}
это очень слабое шифрование)

2023-03-24 09:18 UTC, tmvrus commented on internal/app/handlers.go
> +			return
return потерялся

2023-03-24 09:18 UTC, tmvrus commented on internal/app/handlers.go
> +			return
return потерялся

2023-03-24 09:18 UTC, tmvrus commented on internal/app/handlers.go
> +	logoPass.Login = session.Values["login"].(string)
вот этот кусок встречается много где, хороший кандидат на отдельную ф-ю

2023-03-24 09:18 UTC, tmvrus commented on internal/app/handlers.go
> +		}
return потерялся

2023-03-24 09:18 UTC, tmvrus commented on internal/app/handlers.go
> +	fmt.Println(binaryList)
fmt в качестве логера...

2023-03-28 00:11 UTC, Matthew3000 commented
> * покрытие все еще меньше 80%
> 
>     * множественное дублирования кода
> 
>     * параметры тестов зашиты в код
> 
>     * потерянные return
> 
>     * использование fmt для логирования

Тесты:
1. Тесты
    - добавлены статические тесты в том числе самописный, который (вроде) находит дубликаты кода
    - в имеющиеся добавлена проверка на размер ответа, что позволило найти потерянные returnы
    - добавлена проверка на соответствие задуманному содержимого ответа от сервера в app_test
    - cli_test больше не гадит в консоль fmt.Printом
2. Добавлено скачивание бинарей с клиентом, как сказано в ТЗ. Билд проверен только для windows, он работает. Остальные по идее тоже.
3. Убран дублирующийся код, вынесен в отдельные функции.
4. Статические тесты не дают значимых замечаний
5. Параметры тестов вынесены во флаги при запуске
6. fmt для логирования больше нигде не используется, только для общения
7. Ко всем методам и структурам добавлено описание
8. Шифрование улучшено
9. Необработанные ошибки приёма ответа пользователя теперь обработаны
10. Многочисленные мелкие правки
11. вроде всё норм

2023-03-28 13:25 UTC, tmvrus approved these changes
- fmt.Println для логирования использовать не стоит, это тема 3го спринта
- storage-layer занимается хранением и авторизаций, это нарушает single responsibility
- бессмысленные мьютексы, рекомендую еще раз ознакомиться с теорией 
- не обрабатываются ошибки

+ работает
+ есть логика сравнения UpdatedAt
+ есть миграции

2023-03-28 13:25 UTC, tmvrus commented on cmd/cli/client/local_storage.go
> +	mutex.Lock()
тут тоже самое с проверкой ошибки и мьютексом

2023-03-28 13:25 UTC, tmvrus commented on cmd/cli/client/local_storage.go
> +	mutex.Lock()
и тут

2023-03-28 13:25 UTC, tmvrus commented on internal/storage/access_db.go
> +			}
storage-layer занимается хешированием, а должен заниматься хранением

2023-03-28 13:25 UTC, tmvrus commented on cmd/cli/cli.go
> +					fmt.Println("Update failed due to poor internet connection, continuing offline")
логирование при помощи fmt.Println

2023-03-28 13:25 UTC, tmvrus commented on cmd/cli/client/local_service.go
> +	return nil
логирование при помощи fmt.Println

2023-03-28 14:33 UTC, merged